# Generated by Django 3.2 on 2023-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstudy',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='fieldstudies', to='api.Discipline', verbose_name='Учебная дисциплина'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='studygroups', to='api.Student', verbose_name='Студенты'),
        ),
    ]
